// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/beef/summary": {
            "get": {
                "tags": ["beef"],
                "summary": "Get beef text summary",
                "description": "Retrieves a summary of beef-related text including word count and statistics",
                "produces": ["application/json"],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved beef summary",
                        "schema": {
                            "$ref": "#/definitions/model.SummaryBeef"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.SummaryBeef": {
            "type": "object",
            "description": "Response model containing beef word frequency counts",
            "properties": {
                "beef": {
                    "type": "object",
                    "description": "Map of beef-related words as keys and their frequencies as values",
                    "additionalProperties": {
                        "type": "integer"
                    },
                    "example": {
                        "t-bone": 4,
                        "fatback": 1
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Beef Summary API",
	Description:      "A service that provides summary statistics about beef-related text.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
